// <auto-generated />
using System;
using Infnet.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infnet.Migrations
{
    [DbContext(typeof(InfnetDbContext))]
    [Migration("20250909010305_Inicio2")]
    partial class Inicio2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Infnet.Models.Aluno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_aluno");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DeleteAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("nome_aluno");

                    b.HasKey("Id");

                    b.ToTable("Alunos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "Aluno 1"
                        },
                        new
                        {
                            Id = 2,
                            Nome = "Aluno 2"
                        },
                        new
                        {
                            Id = 3,
                            Nome = "Aluno 3"
                        });
                });

            modelBuilder.Entity("Infnet.Models.AlunoDisciplina", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AlunoId")
                        .HasColumnType("int")
                        .HasColumnName("id_aluno");

                    b.Property<int>("DisciplinaId")
                        .HasColumnType("int")
                        .HasColumnName("id_disciplina");

                    b.HasKey("Id");

                    b.HasIndex("AlunoId");

                    b.HasIndex("DisciplinaId");

                    b.ToTable("AlunosDisciplinas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AlunoId = 1,
                            DisciplinaId = 1
                        },
                        new
                        {
                            Id = 2,
                            AlunoId = 2,
                            DisciplinaId = 1
                        },
                        new
                        {
                            Id = 3,
                            AlunoId = 2,
                            DisciplinaId = 2
                        },
                        new
                        {
                            Id = 4,
                            AlunoId = 3,
                            DisciplinaId = 1
                        },
                        new
                        {
                            Id = 5,
                            AlunoId = 3,
                            DisciplinaId = 2
                        },
                        new
                        {
                            Id = 6,
                            AlunoId = 3,
                            DisciplinaId = 3
                        });
                });

            modelBuilder.Entity("Infnet.Models.Disciplina", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_disciplina");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("nome_disciplina");

                    b.HasKey("Id");

                    b.ToTable("Disciplinas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "Disciplina 1"
                        },
                        new
                        {
                            Id = 2,
                            Nome = "Disciplina 2"
                        },
                        new
                        {
                            Id = 3,
                            Nome = "Disciplina 3"
                        });
                });

            modelBuilder.Entity("Infnet.Models.Email", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_email");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AlunoId")
                        .HasColumnType("int");

                    b.Property<string>("Mail")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("AlunoId");

                    b.ToTable("Emails");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AlunoId = 1,
                            Mail = "aluno1@email.com"
                        },
                        new
                        {
                            Id = 2,
                            AlunoId = 2,
                            Mail = "aluno2@email.com"
                        },
                        new
                        {
                            Id = 3,
                            AlunoId = 2,
                            Mail = "aluno2@gmail.com"
                        },
                        new
                        {
                            Id = 4,
                            AlunoId = 3,
                            Mail = "aluno3@email.com"
                        },
                        new
                        {
                            Id = 5,
                            AlunoId = 3,
                            Mail = "aluno3@gmail.com"
                        },
                        new
                        {
                            Id = 6,
                            AlunoId = 3,
                            Mail = "aluno3@infnet.edu"
                        });
                });

            modelBuilder.Entity("Infnet.Models.Endereco", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_endereco");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AlunoId")
                        .HasColumnType("int");

                    b.Property<string>("Cep")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rua")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("AlunoId")
                        .IsUnique();

                    b.ToTable("Enderecos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AlunoId = 1,
                            Cep = "11111-111",
                            Rua = "Endereço do aluno 1"
                        },
                        new
                        {
                            Id = 2,
                            AlunoId = 2,
                            Cep = "22222-222",
                            Rua = "Endereço do aluno 2"
                        },
                        new
                        {
                            Id = 3,
                            AlunoId = 3,
                            Cep = "33333-333",
                            Rua = "Endereço do aluno 3"
                        });
                });

            modelBuilder.Entity("Infnet.Models.AlunoDisciplina", b =>
                {
                    b.HasOne("Infnet.Models.Aluno", "Aluno")
                        .WithMany("AlunoDisciplina")
                        .HasForeignKey("AlunoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Infnet.Models.Disciplina", "Disciplina")
                        .WithMany("AlunoDisciplina")
                        .HasForeignKey("DisciplinaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Aluno");

                    b.Navigation("Disciplina");
                });

            modelBuilder.Entity("Infnet.Models.Email", b =>
                {
                    b.HasOne("Infnet.Models.Aluno", "Aluno")
                        .WithMany("Emails")
                        .HasForeignKey("AlunoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Aluno");
                });

            modelBuilder.Entity("Infnet.Models.Endereco", b =>
                {
                    b.HasOne("Infnet.Models.Aluno", "Aluno")
                        .WithOne("Endereco")
                        .HasForeignKey("Infnet.Models.Endereco", "AlunoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Aluno");
                });

            modelBuilder.Entity("Infnet.Models.Aluno", b =>
                {
                    b.Navigation("AlunoDisciplina");

                    b.Navigation("Emails");

                    b.Navigation("Endereco")
                        .IsRequired();
                });

            modelBuilder.Entity("Infnet.Models.Disciplina", b =>
                {
                    b.Navigation("AlunoDisciplina");
                });
#pragma warning restore 612, 618
        }
    }
}
