# URL da API externa de detalhes das tranqueiras
tranqueiras.detalhes.api.url=http://localhost:8081

# Porta da aplicação atual no valor padrão para evitar conflito
server.port=8080

# Logging para debug
logging.level.br.edu.infnet.tranqueiras=DEBUG