# Configuração da URL externa do JSON em minha hospedagem
json.external.url=https://wellingtonfalcao.com.br/api/tranqueiras.json

#Configuração do servidor de API
spring.application.name=tranqueira-detalhes-api
spring.cloud.config.enabled=false
server.port=8081