# Configuração do H2 Database
spring.datasource.url=jdbc:h2:mem:deliverydb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Habilitar o console H2 para que você possa ver o banco de dados no navegador
spring.h2.console.enabled=true

# Configuração do JPA/Hibernate

# Isso diz ao Hibernate para deixar o H2 gerenciar o esquema com nosso script
spring.jpa.hibernate.ddl-auto=none

# Isso garante que o schema.sql seja executado na inicialização
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always